version: '3.8'

services:
   db:
    image: postgres:15
    container_name: IdolLog-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5433

volumes:
  postgres_data: